### ISSUE TITLE
NodeJS's child_process.exec() stuck after 'runc create'

### ISSUE THREAD

**Issue by ianpark** [opencontainers/runc#1047]
In NodeJS, child_process.exec('sudo runc create test3', ...) does never callback.
the container instance has been already created when I try 'sudo runc list' though.
child_process.exec might be waiting for the detached child process (init process) of runc, I am not sure why it's stuck. I know it's not runc's bug, but want to understand how runc makes child_process.exec confused.

Does anyone have similar experience? Please enlighten me!

**Comment by cyphar** [comment]
`runc create` will create a container and wait until `runc start` is run. This was changed a few months ago to match the create-start split that occurred in the specification. If you just want to run a container (and don't want to run two separate commands) use `runc run` instead. `runc run` mirrors the old `runc create` functionality.

**Comment by ianpark** [comment]
Hi cyphar, thanks for your comment. Maybe I wasn't clear enough. If you run `run create` in shall, it does not hang so that you can put the following commands like `exec` run `start`. I want to do the same in NodeJS, but `run create` hangs in NodeJS's exec function. Still digging into the problem.

**Comment by cyphar** [comment]
Let me guess, are you using `terminal: false` with your `config.json`? If you are, the reason is that `runc` doesn't close its `stdio` once it detaches -- it is duped over the container process. So if `child_process.exec` is waiting for the child to close `stdout`, it won't happen. You can reproduce a similar hang with:

```
% echo $(./runc create test)
```

You can solve this by using the `--console` flag. However, this is currently being massively rewritten (#1018) and I wouldn't recommend putting the time into learning how to use the old API (which was frankly quite broken). So you can either wait for the #1018 to merge, or you can use that branch for your testing while we're still reviewing it and getting it ready for merging.

**Comment by ianpark** [comment]
I think your guessing is correct. `child_process.exec()` seems to wait until stdout is closed (although NodeJs document says that `callback <Function> called with the output when process terminates.`
I double checked this one using `child_process.spawn()` instead with 'close' and 'exit' events. 'close' is for watching stdout while 'exit' is for watching the process. 'close' is not triggered until I kill the process of the created container. On the other hand, 'exit' is immediately triggered when runc is terminated. Thanks for your help! I owe you a lot.

**Comment by cyphar** [comment]
No problem. :D Do you mind closing the issue if things work now? Or do you have some more questions?

**Comment by ianpark** [comment]
I will close this issue! 👍
