### ISSUE TITLE
proposal: use shfmt for all shell files

### ISSUE THREAD

**Issue by mvdan** [opencontainers/runc#1166]
I've recently written [shfmt](https://github.com/mvdan/sh), a formatter for bash/shell programs. runc is a pretty active project with lots of contributors, so I think it would benefit from its use.

I ran `shfmt -l -w .` and these are the diffs. This does all the files that either have a bash/shell extension or have no extension and a valid bash/shell shebang. By default it indents with tabs.

`git diff` - https://clbin.com/ZvgMY
`git diff -w` - https://clbin.com/Gl1WC

If you have any questions or issues, I'm happy to help. I can also provide a pull request if that would be better.

**Comment by hqhq** [comment]
@mvdan Thanks for offering this, it looks good to me.

@opencontainers/runc-maintainers WDYT?

**Comment by cyphar** [comment]
It looks fine for me, but it will cause conflicts with every PR that is adding tests (which adds a bunch of PR churn). I'm not sure when a good time to merge would be.

**Comment by mvdan** [comment]
FWIW, it should be an easy transition since fixing the PR merge conflicts would be as simple as rebasing while running `shfmt`.

Something like this should work in most cases:

```
git rebase --exec `shfmt -l -w .` upstream/master
```

**Comment by mvdan** [comment]
@hqhq should I do a pull request applying the changes and adding the check to CI?

**Comment by cyphar** [comment]
@mvdan Yeah, sure. I was just worried that we'll need to make several "format fix" PRs (because we might accidentally merge a PR which hasn't been formatted, but we can cross that bridge when we come to it.

Just add the `shfmt` install to the Dockerfile and then modify the `validate` target in the Makefile.

**Comment by rhatdan** [comment]
Shouldn't shfmt be added to some distributions before we add it.  

Is there a standard for formatting of a bash script?

Some of the changes I was not happy with

CMD > /dev/null
to 
CMD >/dev/null

For example.  But I might be bike shedding.

If we change scripts that came from other sources, it might be difficult to merge in newer fixes, or checking what has changed.  But I guess running shfmt on it, would make that easier.

**Comment by cyphar** [comment]
> Shouldn't shfmt be added to some distributions before we add it.

We use bats even though bats isn't packaged by most distributions. For us this doesn't really matter too much -- we can just add another two lines in our `Dockerfile` so that `make ci` works on Jenkins. There's no requirement that distributions run `shfmt` (we -- openSUSE -- certainly won't).

> CMD > /dev/null
> to 
> CMD >/dev/null
> For example. But I might be bike shedding.

I respectfully disagree with this bike shedding. Clearly `>/dev/null` is the objectively superior syntax. :wink:

**Comment by dqminh** [comment]
I'm all for having formatters for all things :p
