### ISSUE TITLE
nsexec memory space for ns

### ISSUE THREAD

**Issue by rajasec** [opencontainers/runc#1178]
@cyphar @hqhq 
in join_namespaces function, after allocating the memory , if there is an error we are bailing out, but the allocated space is not freed. May not be bigger memory leak, do we need to fix ?

**Comment by cyphar** [comment]
`bail` will cause the process to `exit(1)`. IMO there is no real reason to make the code uglier by freeing the memory, because once the process is dead the memory is claimed by the kernel anyway. I don't _really_ care all that much but IMO making all of the statements go from

```
if (condition)
  bail("error");
// something
if (condition)
  bail("error 2");
```

To something like

```

if (condition) {
  free(a);
  bail("error");
}
// something
if (condition) {
  free(a);
  free(b);
  bail("error 2");
}
```

And we can't use `goto error`-style handling because `bail`'s exit code tells us about which bail statement in the source file caused the error.

**Comment by rajasec** [comment]
Agreed. I'll close.
