### ISSUE TITLE
runc on windows?

### ISSUE THREAD

**Issue by hushan** [opencontainers/runc#1186]
runc cannot build on windows(both client and server version) currently, is there any plan to make it work on windows?

**Comment by cyphar** [comment]
runC doesn't have a client or server. It's unlikely that runC will support Windows, simply because it would require a lot of work and nobody wants to do it.

I believe there are projects to get an OCI runtime for windows though (Microsoft is part of the OCI after all). Most of the work I've seen so far exists within Docker (not inside OCI runtimes).

**Comment by hushan** [comment]
i see, thanks, it was several stub classes for windows under libcontainer makes me think that windows support is under development.
