### ISSUE TITLE
I want to build runc against libc-2.12.so instead of libc-2.14.so

### ISSUE THREAD

**Issue by Nabarun** [opencontainers/runc#1299]
Hi 

In my machine I am getting this error when executing runc. I don't want to install glibc_2.14. 
runc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by runc)

Is there a way to build runc on older version of glibc 
/lib64/libc.so.6 -> libc-2.12.so

Thanks 
Nabarun

**Comment by cyphar** [comment]
Have you tried building it yourself? The binary releases are only done for convenience, and I would **always** recommend that you use the source and build it yourself. Unless you're using a distribution package, in which case you should make a bug against your distribution?

Unfortunately we cannot statically compile runC because Go doesn't allow statically linking code that uses `cgo`.

**Comment by crosbymichael** [comment]
@Nabarun yes, like @cyphar said, you can build runc yourself if you don't want to use the libc version that is compiled in the binaries.  Your distro should have the correct versions for you but if you have something more advanced then you should compile your own binaries.
