### ISSUE TITLE
broken console support on ppc64le

### ISSUE THREAD

**Issue by qiancai** [opencontainers/runc#1364]
eea28f480db435dbef4a275de9776b9934818b8c broke console support on ppc64le.

`# runc run spec`
Confirmed terminal: true is there in config.json 

`# runc run root`
`container_linux.go:247: starting container process caused "process_linux.go:384: container init caused \"ioctl(tty, tcgets): inappropriate ioctl for device\""`

Reverted the above commit makes thing works again.

@cyphar FYI

**Comment by harche** [comment]
Thanks for reporting the issue. Looking into it.

**Comment by harche** [comment]
Can you provide the output of, 

`stty -a`

**Comment by cyphar** [comment]
I think the issue is that the `ppc64le` `ioctl`s are different to `x86_64`. Which is great fun, because Go doesn't provide any front-end to `ioctl`s...

**Comment by qiancai** [comment]
# stty -a
speed 38400 baud; rows 24; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; flush = ^U; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke

**Comment by clnperez** [comment]
It turns out the scripts used to auto-generate TCGETS and TCSETS in go have a bug. If definitely needs to be fixed -- but the better solution is to use x/sys/unix instead of syscall. We've confirmed that they are correct for ppc64le there. I've started a PR to switch runc over (as you can see in the above commit links) but something isn't quite right (tests failing with "operation not supported") so I'll try and get that figured out.

You can also see more discussion in golang/go#19560.

**Comment by crosbymichael** [comment]
@clnperez That sounds like a good plan, switching over to `sys/unix`

However we should probably do this incrementally in a series of PRs and not one large PR switching the entire project over to that package.  As sub-packages, functionality gets ported over and it has been verified to work, feel free to open PRs so that we can merge these changes as we go.

**Comment by clnperez** [comment]
@crosbymichael would you recommend moving just a few files at a time (e.g. the ones using the values we know are wrong)? Or maybe all of libcontainer? 

I'm a little worried about porting over bits of the project since sys and syscall have different values for things like TCGETS. 

I did change just the console bits in another patch, and ran the tests on both x86 and power. The tests all passed in my x86 env but not the power env. I re-ran the tests against master in my power vm, and at least the same tests failed for both master and my patch. So, I guess, I'll submit the initial fix that fixes the console issue only for now? Maybe we can open a broader issue for fixing other tests on power -- and another issue for porting the rest of the project to x/sys.

WDYT?

FYI, the new patch (potential PR): https://github.com/clnperez/runc/commit/ddf44863b6fabaebbd07f72105b265cf2c6e8b52

**Comment by crosbymichael** [comment]
@clnperez Ideally the final result is that all of libcontainer and runc are ported over.  

Be doing this in one PR will be hard to test and review.  We can do it package by package to make sure we don't hit any regressions and we have small, review-able prs to merge.

**Comment by clnperez** [comment]
@crosbymichael I just had it pointed out to me that libcontainer isn't one big 'libcontainer' package. Sorry I didn't get what you were trying to say earlier. 😸
