### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by rucuriousyet** [opencontainers/runc#1391]
I love Golang, would love to help with an awesome project like this! How can I get involved?

**Comment by razic** [comment]
@rucuriousyet Hey! I am kind of in the same boat as you. What I recommend is that you use Docker until you run into something that doesn't work quite right, or a feature that is missing. Take the moment as an opportunity to fix something that directly affects you. I found this approach to be more fulfilling,  as opposed to aimlessly trying to find something to work on. You may also want to close out this issue, since it's not really an issue, and the folks working on this are extremely busy! Just my two cents :)

**Comment by crosbymichael** [comment]
I think the best way to get started in any project is to look though the issue tracker, grab one, and complete it.

**Comment by razic** [comment]
@rucuriousyet fwiw, for myself, there was somewhat of a learning curve to understand the architecture behind containerd. if you are already familiar with grpc, oci/runc, and golang, then jumping in will be a little easier. still, there are things like the `shim` which, if explained, can really speed up the learning curve. 

the guy who posted above is one of the leads on this project and is super smart. i very strongly recommend watching his talk about building a container supervisor:

https://youtu.be/VWuHWfEB6ro

i've probably watched that video about 5 times. it's been the single most valuable resource for me to jump directly into the code.

additionally, you can drop your head in the #containerd slack channel and talk everyone. you have to sign up for an invite here:

https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/

lastly, i am more than happy to answer any questions you may have to help in any way :)

**Comment by hqhq** [comment]
I guess both @razic and @crosbymichael gave constructive suggestions, I'll close this issue, feel free to comment and ask any questions if you still have any.
