### ISSUE TITLE
No way to determine exit code of the program

### ISSUE THREAD

**Issue by kaoet** [opencontainers/runc#1459]
First start a container with `--detach` option.

After a few minutes, the container exits. Then inspect it with `runc status`:
```
{
  "ociVersion": "1.0.0-rc3",
  "id": "5927dc3293614308894a5de5",
  "pid": 34915,
  "bundlePath": "/run/unsullied/5927dc3293614308894a5de5",
  "rootfsPath": "/mnt/shared/nfshomes/.rootfs/58d8dc5be283e2eaacce766a",
  "status": "destroyed",
  "created": "2017-05-26T07:41:44.910843814Z"
}
```

As you can see. I can only known it was "destroyed", but cannot determine the exit code. Thus I don't know if it exited normally.

**Comment by cyphar** [comment]
This is expected. The design of `runc` is such that we don't have any long-running processes (the only process alive when you do `--detach` is your container init process -- none of our code is running).

If you want to get the exit code then the parent of your container init (which will be the parent of the runc process though you might need to set `PR_SET_CHILD_SUBREAPER`) can get it through the normal `SIGCHLD` process. In the case of `runc` without detaching this isn't an issue (because `runc` then acts as that higher layer).

While this doesn't seem ergonomic, `runc`'s design means that a higher layer can impose their own opinionated view on how the container init process should be handled.

**Comment by dqminh** [comment]
Yah this is expected with `--detach`. For example about how to listen to `SIGCHLD` and reap the process, you can take a look at https://github.com/containerd/containerd
