### ISSUE TITLE
exec --detach should not print any output if no console is provided

### ISSUE THREAD

**Issue by sboeuf** [opencontainers/runc#1525]
Let's say we have a running container and we want to execute a new command with `exec` command, in case we choose the `--detach` option, I think we don't expect any output on the shell used to start this command. Unfortunately, I get some outputs in the case I also have this flag enabled `--tty=false`.

Let me take an example. If I do (where 12345 is the container ID):
```
runc exec --detach --tty=true 12345 echo hello
```
I get the following error as expected (we could also have no error but not output anything):
```
exec failed: cannot allocate tty if runc will detach without setting console socket
```

But in case I start this:
```
runc exec --detach --tty=false 12345 echo hello
```
I get the following output
```
hello
```
I get my terminal back but I should not get this output.

I made the same test with `/bin/top` command and it was more explicit about the issue. Indeed, still in case of `--tty=false`, I was getting my terminal back but every 2 seconds, I got the output coming from the `top` command.

I think that as long as we detach the command, whatever the value of `--tty`, we should not get any output, unless we provide a specific console-socket to which we expect to receive this output.

Any thoughts ?

**Comment by sboeuf** [comment]
https://github.com/kubernetes-incubator/cri-o/issues/659

**Comment by mrunalp** [comment]
I think it makes sense to require a console socket when detach is set.

@cyphar @crosbymichael WDYT?

**Comment by cyphar** [comment]
No, because `--tty=false` with `--detach` means that `runc`'s stdio file descriptors or just passed down to the container. This happens with `exec`, `run` and `create` and is by design so that users can set up their own TTYs.

It is true that this is confusing because you have four very different modes with mixes of `--tty` and `--detach` (some requiring `--console-socket`, some not). But in order to fulfil all of the requirements (for example, how `crio` uses `run`) we need to have the stdio passing feature.

**Comment by sboeuf** [comment]
But if users want to setup their own TTYs, you should have kept `--console` instead... That was the point of this flag, that is providing the slave path of your own TTY pair. This is really confusing and not very logical. If you are detached, nothing should be printed unless there is a console specified...

**Comment by sboeuf** [comment]
Close this issue as this is a known and wanted behavior.

**Comment by cyphar** [comment]
@sboeuf `--console` didn't do what you probably think it did. The reason for this change is that we wanted to create `pty`s inside a container, which means that `--console-socket` came about (and `--console` didn't make sense anymore). But this behavior existed before `--console` (it's existed ever since `--detach` and especially since `create`/`start`).

**Comment by sboeuf** [comment]
I believe you it is something that's here from the beginning. But that's basically what's `--console` was doing if you were providing the slave path on your own. I agree `--console-socket` is nice because you don't have to bother with the pty pair creation. But I think that having both `--console` and `--console-socket` could work, and it would remove confusion in case we would consider that detach could get some output only when a console is provided.
