### ISSUE TITLE
Can container run in host network mode

### ISSUE THREAD

**Issue by panpan0000** [opencontainers/runc#1552]
the motivation comes from https://github.com/concourse/concourse/issues/1455

I'm using Concourse, which leverage garden/runc to spawn container for CI test.

But I wonder if there's a  similar usage like docker-engine's ```--network="host" ```
so that containers can reach the hosts'  network NICs (to provide DHCP , PXE ...etc to other machines )

Thank you.

**Comment by cyphar** [comment]
Yes, if you remove the `network` entry from the `config.json` `runc` will not create a new network namespace and will thus be using the host's network namespace (just like a normal process in the host would).

**Comment by williammartin** [comment]
@panpan0000 Not sure you need an issue against runc, which will support this already. What we'd need to do is provide a way in Garden for Concourse to request this. Suggest you open an issue against https://github.com/cloudfoundry/garden-runc-release and we can discuss this because right now Garden is quite opinionated and will always put your container in a new network namespace.

**Comment by panpan0000** [comment]
Thank you both @cyphar , @williammartin 
I've posted https://github.com/cloudfoundry/garden-runc-release/issues/43 against garden.
thank you all.
