### ISSUE TITLE
question of runc init process and namespace

### ISSUE THREAD

**Issue by IT-huang** [opencontainers/runc#1581]
func (p *initProcess)  start()   of  libcontainer/process_linux.go ,as I know p.cmd.Start() to start runc init process  asynchronous.And use this init process to set namespace (such as pid、uts )according unshare syscall . However  when i debug p.execSetns() ，I find  pid of  json.NewDecoder(p.parentPipe).Decode(&pid)  include two pids(like  5034 5035)  actually.And runc always choose the process of pid 5035 to be the container process .how 5034 come?Can anyone tell me some details?

**Comment by hqhq** [comment]
@IT-huang It's a intermediary process we created when handling new process and namespaces, you can refer to `libcontainer/nsenter/nsexec.c`, function `nsexec()` has very comprehensive comments about why we're doing like that.

I'm going to close this since it's not an issue, let me know if you have more concerns, and if you have more questions, mailing list https://groups.google.com/a/opencontainers.org/forum/#!forum/dev would be a better place to discuss or get help from.

**Comment by IT-huang** [comment]
@hqhq 
Hi，Qiang Huang ：
    Recently，I write a new namespace for my project.I want to add it to runc and docker.I modify docker oci/ and runc libcontainer/configs/namespace_linux.go and namespace_syscall.go.Also I add Clone defination to nsenter.Then I can correctly start my container.However I cannot docker exec and get error "oci runtime error: exec failed: container_linux.go:306: starting container process caused "read init-p: connection reset by peer",And I debug my code and find namespaces[i] does not have usernamespace path.I wonder if you can help me and tell me if i want to add a new namesapce what should i do to runc?
