### ISSUE TITLE
How to translate the following docker run command into runc?

### ISSUE THREAD

**Issue by sourav295** [opencontainers/runc#1684]
I am stuck trying to convert the following command to runc

docker run --name dc-server --net caching_network -d cloudsuite/data-caching:server -t 4 -m 4096 -n 550

I am aware that I have to acquire a root filesystem from the existing Docker container (that being cloudsuite/data-caching:server), but after that how do I attach it to the caching_network (which is a docker overlay network), and pass along the other parameters.

I am using Docker version 17.12.0-ce.

Cloudsuite documentation
http://cloudsuite.ch/pages/benchmarks/datacaching/

**Comment by cyphar** [comment]
In order to set up a network, you need to use hooks. Docker uses `docker-libnetwork` as the hook process under the hood, but I don't think it's precisely user-friendly. To get an idea of how you might use hooks to set up a network, look at Jess's [netns](https://github.com/jessfraz/netns). You can use a similar principle with [CNI plugins](https://github.com/containernetworking/cni) to connect a container to a CNI network.

**Comment by frezbo** [comment]
@sourav295 you can try using this: https://github.com/jessfraz/riddler/ to convert docker commands to OCI spec

**Comment by sourav295** [comment]
Thanks for the answers. Do you believe it will work with a docker overlay network built on top of a swarm network?
