### ISSUE TITLE
Cant create a static binary on Fedora 27

### ISSUE THREAD

**Issue by frezbo** [opencontainers/runc#1689]
Hi,

I am trying to create a static binary on Fedora 27, its failing with this error:

```runc (aws:default)(git:master)$ make static
CGO_ENABLED=1 go build  -tags "seccomp netgo cgo static_build" -installsuffix netgo -ldflags "-w -extldflags -static -X main.gitCommit="ab4a8191679806893207d9c1e507a77ff46dafaa" -X main.version=1.0.0-rc4+dev " -o runc .
# github.com/opencontainers/runc
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lseccomp
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

make: *** [Makefile:42: static] Error 2
runc (aws:default)(git:master)$ 

```
But the dynamic binary and creating inside a golang alpine container works, can anyone help me with this. seccomp-devel packages are already installed.

**Comment by cyphar** [comment]
You need to have the relevant **static** libraries (these are different from the `.so`s that you have installed). I don't know what the packages are called on Fedora, but on openSUSE they would be:

* `glibc-devel-static` which maps to `-lc` and I believe it'll also include `-lpthread`.
* Most distributions don't ship a static version of `seccomp` (because it's considered a security vulnerability as the distribution cannot update `seccomp` for binaries compiled statically). However, Fedora *might* have it and it's probably called `seccomp-devel-static` or `libseccomp-devel-static` or something like that. You can also disable seccomp support by removing it from the `-tags` section.

**Comment by frezbo** [comment]
@cyphar  Thanks for the pointers. I found the packages. Adding below for reference:

- glibc-static
- libseccomp-devel


Closing this issue.
