### ISSUE TITLE
JoinSessionKeyring fails if KeyctlJoinSessionKeyring returns ENOSYS

### ISSUE THREAD

**Issue by dhiltonp** [opencontainers/runc#1889]
TBH, I don't entirely understand the problem, chromium has this in their bug tracker 'to track an upstream solution', yet I didn't see any matching issue here.

https://bugs.chromium.org/p/chromium/issues/detail?id=860565#c10

https://github.com/opencontainers/runc/blob/master/libcontainer/keys/keyctl.go#L15

**Comment by cyphar** [comment]
I believe it's because LXC uses a seccomp profile to make all of the keyring syscalls return `ENOSYS` (clever actually, since userspace shouldn't be silly and fail on `ENOSYS` -- but obviously we are being silly here).

Since we already have a `--no-new-keyring` flag to support old kernels really we should just detect `ENOSYS` and thus ignore it (probably logging a warning).

*However* the primary motivation for creating a keyring in the first place (from memory) is that they are not namespaced, but joining a new keyring means you cannot access the old one (and joining requires privilege) -- so at least it's a bit harder to list the host keyring. So it's arguably a security justification, so maybe just ignoring it isn't the best idea? I'll look through the relevant kernel code to see why exactly we're doing this.
