### ISSUE TITLE
Met error when using go-lang(os/exec.Command) to run runc command.

### ISSUE THREAD

**Issue by zenlinTechnofreak** [opencontainers/runc#190]
Hi， I have try to use golang to run "runc" comand,as below,
``` go
cmd := exec.Command("/bin/bash", "-c", "runc")
	_, err := cmd.Output()
	if err != nil {
		log.Fatalf("........................................... error, %v", err)
	}
``` 
when I use golang to exec other programme, it is normally.

In my project, I prefered to use golang to run runc, so can anyone help me to do that.

Anyway, I have try to pakage running runc in a shell file ,and then use golang to call the shell.
It was also failed, like,
in test_runc.sh
``` sh
#!/bin/bash
 runc
```
called by golang
``` go
	cmd := exec.Command("/bin/bash", "-c", "./test_runc.sh")
	_, err := cmd.Output()
	if err != nil {
		log.Fatalf("........................................... error, %v", err)
	}
```

#### It seems like, runc have some different with other main programmes, can anyone help me to fix it out?

**Comment by hqhq** [comment]
If we use runC instead of libcontainer in Docker one day, the usage would be something like lxc does https://github.com/docker/docker/blob/master/daemon/execdriver/lxc/driver.go#L175. In command level, your usage would be fine. 

But I think it would be a bit complicate to make runC work in that way, because runC still use libcontainer's mechanism, which uses reexec to run containers, in sample words, it depends on `os.Args[0]` to get the reexec entry to call `StartInitialization`.

I don't know if there is a sample way to make runC work in golang command, hope we can get some light from expert maintainers.

**Comment by LK4D4** [comment]
Not sure what do you mean here. Maybe better to provide examples of errors, next code works for me:
```
package main

import (
	"log"
	"os"
	"os/exec"
)

func main() {
	cmd := exec.Command("runc")
	cmd.Stderr = os.Stderr
	cmd.Stdout = os.Stdout
	cmd.Stdin = os.Stdin
	if err := cmd.Run(); err != nil {
		log.Fatalf("Start: %v", err)
	}
}
```

**Comment by zenlinTechnofreak** [comment]
@LK4D4 @hqhq   I am going to have a try about that, thanks.

**Comment by zenlinTechnofreak** [comment]
@LK4D4  I just missed the ``` go cmd.Stdin = os.Stdin```, thanks.

**Comment by hqhq** [comment]
Great, I would reread the code to see how it handle `os.Args[0]` in this situation.
