### ISSUE TITLE
CVE-2019-5736

### ISSUE THREAD

**Issue by userlooooser** [opencontainers/runc#1985]
runc < 1.0-rc6 (Docker < 18.09.2) - Container Breakout (2) exploit source is aviable on Exploit-DB and other exploit database sites, please, fix it in minor/major update.
Thanks.
https://www.exploit-db.com/exploits/46369

**Comment by cyphar** [comment]
It's already been fixed in 0a8e4117e7f715d5fbeef398405813ce8e88558b -- I was the person who organised the embargo (and allocated the CVE) and wrote the modified exploit code now in @feexd's repository. A new version will be pushed when #1984 is merged (and possibly once we find a solution for #1980).
