### ISSUE TITLE
Perform security audit on runc code base

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/runc#2100]
The OCI is interested in funding a security audit on runc.

There is budget and we will scope the audit. The containerd project went under an audit not so long ago and this will be a similar exercise: https://github.com/containerd/containerd/blob/master/docs/SECURITY_AUDIT.pdf

**Comment by crosbymichael** [comment]
Sounds good to me!

**Comment by cyphar** [comment]
Sounds like a good idea -- I wonder if they will agree with where I think the really weak points of runc lie. Though I will mention that I am a little bit surprised that the containerd security audit only found one low-risk issue after a >2 week audit. I have my own suspicions that there are several pretty major issues in both runc and containerd, but the audit claims that the majority of issues you would hit in a Go program are just race conditions and logic errors -- but container runtimes have different security properties and concerns to generic Go programs. (I am working on fixing some of those issues before we see actual exploits of them, but there's only one of me so it's taking a while.)

**Comment by crosbymichael** [comment]
And I have suspicions that `sudo` has major security issues...

Security is never finished and is something that has to be worked on constantly.  Its needs maturity in developers and external parties to audit and fix things.  containerd has many mature developers and people who work constantly on the project to keep things robust and secure.  If you find issues, report them in the correct channels and get help.  Security is a process and how you find, audit, fix, and release in a robust and responsible manner shows the maturity of a project, it's not about never having exploits.

**Comment by cyphar** [comment]
I didn't mean to imply that I think containerd is bad software or anything like that. Nor am I at all saying that "having no exploits" is a good badge to carry (not having any exploits discovered means nobody has looked hard enough, not that there aren't any).

My point was that I was honestly surprised that a >3 week audit only found one low-level flaw -- and I was wondering (aloud) what the reason for that was (my guess would be that the kinds of bugs they were looking for were not the best ones to focus on, because container runtimes are very different to most other typical Go programs). I'd be tentatively willing to bet that if you spent 3 weeks with 6 people auditing `sudo`, you would likely find more than a low-level configuration flaw. That doesn't make `sudo` bad either, by the way.

But this is all besides the point, I agree we should do an audit even if it does only end up finding minor issues.
