### ISSUE TITLE
How to check the version of runc corresponding to docker

### ISSUE THREAD

**Issue by hwdef** [opencontainers/runc#2225]
I want to find the verison of runc corresponding to docker 19.03.5

**Comment by cyphar** [comment]
[It's buried in their build scripts.](https://github.com/docker/docker-ce/blob/v19.03.5/components/engine/hack/dockerfile/install/runc.installer#L7) Just note that `runc` isn't a Docker project, so this is a question which is better suited for the Docker community (I only happen to know because I maintain Docker for (open)SUSE).

**Comment by hwdef** [comment]
Thank you very much !
