### ISSUE TITLE
RFC: pull approve: set reset_on_push to false

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2245]
https://github.com/opencontainers/runc/blob/6503438fd6b0415bc146403b30b8a248b3346f52/.pullapprove.yml#L4

To facilitate merging PRs,  I suggest setting `reset_on_push` to false.

**Comment by AkihiroSuda** [comment]
@cyphar @caniszczyk WDYT?

**Comment by cyphar** [comment]
To be honest, I don't like this idea -- if someone pushes new code to a branch it should require re-reviewing IMHO.

**Comment by AkihiroSuda** [comment]
> if someone pushes new code to a branch it should require re-reviewing IMHO. 

Small changes (e.g. typo, format, addition of code comments) should not?

**Comment by AkihiroSuda** [comment]
Also, trivial git rebase should not require re-reviewing?

**Comment by AkihiroSuda** [comment]
@kolyshkin WDYT?

**Comment by kolyshkin** [comment]
Frankly speaking, I do not see any added value in using pullapprove at all, since github has its own way to approve or reject changes, it's easy to use and the current approval status is clearly visible). It is also possible to re-request a review if a PR owner (or any maintainer) feels the recent changes in PR are major enough to do so (and by default it is working as @AkihiroSuda wants pullapprove to be, i.e. re-review is not required).

So, to my mind, the "two LGTMs from maintainers are required to merge" rule is good enough, together with github own "review changes" mechanism and decent maintainers.
