### ISSUE TITLE
enhance cpu-shares/cpus option

### ISSUE THREAD

**Issue by 2qif49lt** [opencontainers/runc#2349]
When run a container with cpus=4 option in a machine with  lots of hard cores , the container's /proc/cpuinfo's content are same as machine's.

This is going to encounter trouble in some common sence like that C++ programer code `std::thread::hardware_concurrency` usually to fetch core numbser to start work threads. 

As above,  programer mean to start 4  work threads  at most, but it boom in my K8S cluster server with 48 cores (resourse limit 4C).   especially the program is the high performance whose threads contend with no lock will waste extra resources .

**Comment by kolyshkin** [comment]
Unfortunately, this is out of control of runc, since the /proc/cpuinfo file is served by the Linux kernel. As many `/proc` files, this one is not "virtualized" so it shows the same info as on the host.

You should use `sched_getaffinity(2)` syscall to get the number of cpus available. Check the `nproc(1)` utility.

**Comment by kolyshkin** [comment]
Also, feel free to file a bug against libstdc++

**Comment by kolyshkin** [comment]
(or not, since it says "hardware" and returns the hardware cpus, while you are limited by linux kernel cpuset controller.
