### ISSUE TITLE
cgroup2: Revert "CreateCgroupPath: only enable needed controllers"

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2367]
`CreateCgroupPath: only enable needed controllers` (4b4bc995ad4ee4679ffbe38f1672be01c24256fc) seems problematic toward supporting nested containers. (#2356)

As many controller s as possible should be always enabled.

cc @kolyshkin

**Comment by AkihiroSuda** [comment]
@kolyshkin WDYT?

**Comment by kolyshkin** [comment]
Enabling a controller should negatively affect performance (since some accounting for the resource(s) controlled are to be done by the kernel) -- even in the case no limits are set.

So, this is a trade-off between best performance and versatility. Ideally, I'd like it to be configurable (i.e. there should be a way to just enable a controller but do not set any limits, which is currently impossible).

Until we have this ability, either way is fine with me (all controllers or on-demand). Since we used to have all controllers, let's do that.

**Comment by AkihiroSuda** [comment]
resolved in https://github.com/opencontainers/runc/pull/2395
