### ISSUE TITLE
add `shfmt` to CI

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2396]
We should validate indentation issues of shell scripts (mostly bats) in CI
https://github.com/moby/moby/blob/master/hack/validate/shfmt

**Comment by kolyshkin** [comment]
This is going to be a problem with bats files, and bats is not exactly shell. In particular, it complains like this:

> tests/integration/create.bats:25:1: "}" can only be used to close a block

since it does not recognize

> @test "runc create" {

as a function.

Surely we can find some workaround such as replacing `@test "some thing"` lines with `function some_thing()` and then replacing it back....

**Comment by cyphar** [comment]
This is why I'm personally a bit worried about re-adding `shfmt` to the CI -- the "shell files" we want to test are actually not normal shell programs, and in addition we've had problems with `shfmt` changing their "best practice" rules in the past (breaking the CI). This might not be a problem anymore, but we should keep it in mind.

**Comment by kolyshkin** [comment]
FIled https://github.com/mvdan/sh/issues/600
