### ISSUE TITLE
How to run cpp or python code in runc container?

### ISSUE THREAD

**Issue by gitsvm** [opencontainers/runc#2556]
I don't know what to add in `args` parameter in `config.json` file to be able to run my code in `cpp` or `python`? file is present in root inside `rootfs` folder.

currently my args parameter is this:

```
`		"args": [
			"sh",
			"-c",
			"hello.cpp"
		],`
```
it is giving following error on running the container using `sudo runc run <cid>`:
`ERRO[0000] invalid character '/' looking for beginning of value
`
This is my cpp file:

```
#include <iostream.h>
//#include <stdio.h>


using namespace std;

int main(int argc, char const *argv[])
{
	cout<<"Hello world\n";
	/* code */
	return 0;
}
```

**Comment by AkihiroSuda** [comment]
You can't run a cpp program with sh -c, you need to compile it with a compiler like g++.

For how to compile cpp programs, https://stackoverflow.com and similar sites are the right places to ask.

The runc error is probably due to a typo in config.json

**Comment by ashwani29** [comment]
> You can't run a cpp program with sh -c, you need to compile it with a compiler like g++.
> 
> For how to compile cpp programs, https://stackoverflow.com and similar sites are the right places to ask.
> 
> The runc error is probably due to a typo in config.json

Please tell in steps in how can i acheive this. 
what i got from your answer is that first i've to compile my cpp program. Then what needs to be done? what should i put in args parameter so that runc will be able to run this program in a container?

**Comment by gitsvm** [comment]
@AkihiroSuda

**Comment by cyphar** [comment]
I'd like to point out that this is a bug tracker for a project, and while I am going to go out of my way to answer your question (despite the spam in #2557, checkpoint-restore/criu#1185, checkpoint-restore/criu#1184) this really isn't the right place to ask these types of questions -- there are programming language forums where you might be able to get more help.

First off, you don't just "run" a C++ program -- you need to compile it first. If you aren't sure how to do this, then you'll need to consult resources like StackOverflow and possibly whatever education materials you're using to learn C++ (though for your example program it would look like `g++ -o program program.cpp` assuming you have GCC installed).

As for running things in containers, I'm not sure whether you are using a distribution `rootfs` (such as Ubuntu) or if you've just created an empty directory. Most programs require a normal-ish distribution in order to function properly (especially Python), so you should start with an existing distribution and build from there. Assuming you have everything set up correctly, you just have to update your `args` to just be `"args": ["/program"]` if the program you wish to run is in `/` of the container.

There are tools to do this (`skopeo and umoci`) which you can combine with `runc` to accomplish what you want but I get the impression that you're new to containers -- in that case, I would suggest using something which is less complicated to use (such as Docker -- which has a [getting started guide](https://docs.docker.com/get-started/)).

`runc` is a fairly low-level project and I'm not sure why you feel the need to use it directly -- Docker (as well as most other container runtimes) uses `runc` internally.

**Comment by gitsvm** [comment]
@cyphar Thanks for the answer, this also i tried to do but getting below error: 
```
user@user-HP-Pavilion-Notebook:~/ctr2$ sudo runc run ctr2
[sudo] password for user: 
standard_init_linux.go:211: exec user process caused: no such file or directory
```
ctr2 is the container id here.

while i can see my program is in `/` inside `rootfs` folder.
```
user@user-HP-Pavilion-Notebook:~/ctr2/rootfs$ ls
bin  etc    hello.cpp  proc  script.sh  tmp  var
dev  hello  home       root  sys        usr
user@user-HP-Pavilion-Notebook:~/ctr2/rootfs$ 
```

This `rootfs` folder is created by following instructions as told in the `Creating an OCI Bundle` section in the Readme.md.
Why is it giving this error? If i run `script.sh` file it runs but cannot run object file `hello`. Gives the above error.

**Comment by cyphar** [comment]
You can't use busybox as a base for running binaries you compiled on a complete distribution -- it doesn't have any shared libraries installed and so your `hello` binary can't run (the "no such file or directory" error is actually telling you that it couldn't find `/lib/libc.so.6`). You can either compile your binary statically, or use a full distribution as your base (my comment that you should should probably be using Docker or something like that still stands).

**Comment by gitsvm** [comment]
I've to work on `CRIU` source code, as `CRIU` is unable to dump and retsore a container on my machine, it always gives error like `unreachable sharing` even after adding the option of `--enable-external-master` & `--enable-external-sharing` so i'm using runc to checkpoint/restore as it internally uses CRIU only. where i can get this complete distribution instead of busybox? i can use same command `docker export` to export it into rootfs directory?
and does docker uses criu, can criu dump/restore a docker container?

**Comment by cyphar** [comment]
> where i can get this complete distribution instead of busybox?

Just use Ubuntu. Rather than doing `docker create busybox` do `docker create ubuntu`. We really should update that example...

> and does docker uses criu, can criu dump/restore a docker container?

Docker doesn't support CRIU AFAIK, so I guess you have to use runc directly if you need checkpoint-restore.

**Comment by AkihiroSuda** [comment]
Docker supports criu https://technology.amis.nl/2018/04/08/first-steps-with-docker-checkpoint-to-create-and-restore-snapshots-of-running-containers/

**Comment by gitsvm** [comment]
> > where i can get this complete distribution instead of busybox?
>
> Just use Ubuntu. Rather than doing `docker create busybox` do `docker create ubuntu`. We really should update that example...
>
Thanks, I tried this, now as i've to install g++ inside my container rootfs to compile that cpp program, i run the container and it opens a shell like environment.
 I did `apt install g++`, it gives an error:
`E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?` writing yes prints a 'y' character on the screen infinitely, and if using sudo as a prefix, it gives an error of `sh: 7: sudo: not found`
what should i do now?

**Comment by gitsvm** [comment]
I  just run the container to see error but surprisingly there is no error, it prints hello world. How is this happening? 
I guess it just runs the binary but when it comes to compile any file, it cannot do so as it doesn't have g++. Is it correct?

**Comment by cyphar** [comment]
> I guess it just runs the binary but when it comes to compile any file, it cannot do so as it doesn't have g++. Is it correct?

Yes. There are lots of reasons why it might be failing to install `g++` (not running as root, having terminal creation disabled, no networking, being a read-only container, and so on) -- as I discussed above I'd suggest you use Docker (now that @AkihiroSuda has corrected me -- Docker supports checkpoint-restore and honestly `runc` isn't a tool meant to be used by folks who are not deeply familiar with containers and Linux -- it's just not aimed at general users).
