### ISSUE TITLE
Contributing doc missing

### ISSUE THREAD

**Issue by pnasrat** [opencontainers/runc#26]
It is unclear if this project requires DCO signoff

http://developercertificate.org

At the very least there should be a CONTRIBUTING.md

**Comment by mattfarina** [comment]
I'd argue this needs to be handled asap because [libcontainer](https://github.com/docker/libcontainer/blob/master/CONTRIBUTING.md) and [rkt](https://github.com/coreos/rkt/blob/master/CONTRIBUTING.md) both required certificates of origin.

Since this brings them both together I would expect a DCO is required.
