### ISSUE TITLE
Does getCgroupMountsHelper() returns subsystem for mounts which hasn't subsystem?

### ISSUE THREAD

**Issue by b10s** [opencontainers/runc#2680]
Hello runc folks,

The question is more theoretical and have no practical implication so far for me.

The value returned from `getCgroupMountsHelper` function is an array of maps, e.g.:
```
[
        {
                Mountpoint: "/sys/fs/cgroup/systemd",
                Root: "/",
                Subsystems: []string len: 1, cap: 1, ["systemd"],},
        {
                Mountpoint: "/sys/fs/cgroup/memory",
                Root: "/",
                Subsystems: []string len: 1, cap: 1, ["memory"],},
        ...
]
```

Each map has a key `Subsystems` and it's value is an array of cgroups subsystems attached to the mountpoint.

However the [cgroups documentation](https://man7.org/linux/man-pages/man7/cgroups.7.html) says that mounts like `/sys/fs/cgroup/systemd` might be without attached subsystems:

![Selection_999(093)](https://user-images.githubusercontent.com/4618288/98984869-1ab69f80-2566-11eb-98c9-f1b704580622.png)

Here is a mount taken from `/proc/self/mountinfo` which mentioned above in getCgroupMountsHelper returned value:
```
26 25 0:23 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:6 - cgroup cgroup rw,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd
```

Terminology note. Seems we can use interchangeably terms subsystems and controllers:

![Selection_999(092)](https://user-images.githubusercontent.com/4618288/98983461-23a67180-2564-11eb-884f-2aa49ee70c5d.png)

----------------------------

So the question is: does `getCgroupMountsHelper()` returns subsystem for mounts which has not subsystem or did I miss something?

**upd:** kernel.org doc might be useful as well:
> When passing a name=<x> option for a new hierarchy, you need to specify subsystems manually

https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/cgroups.html#mounting-hierarchies-by-name

**Comment by kolyshkin** [comment]
@b10s as you can see from `TestGetCgroupMounts` (libcontainer/cgroups/utils_test.go), it works for systemd cgroup mountpoint as well, if this was your question. It works in pair with `ParseCgroupFile` which creates a map consumed by it.

As for your commit (https://github.com/b10s/kubernetes/commit/2f35ad5de9d97d189422dda93f3431ff46cc6358), it does not seem right since in some setups there are multiple cgroup hieararchies. I haven't seen it myself in the wild, but there's `bedrockMountinfo` in libcontainer/cgroups/utils_test.go which you might want to take a look at.

Finally, all this is quite complicated and twisted, and I am looking forward to the day cgroupv2 will be used by default, it makes things much more simple (and is already fully supported by both the kernel and the runc).

**Comment by kolyshkin** [comment]
I guess we can close this one
