### ISSUE TITLE
Is runC alone suitable for a production environment?

### ISSUE THREAD

**Issue by Andreyooo** [opencontainers/runc#2702]
I'm a beginner in the container world and was wondering if runC alone is suitable for a production environment.

We need a lightweight implementation for containers and dockers daemon interface has to much overhead, so the idea was to export the docker image and run it with runC.

Is there something to watch out for? We intend to only run one container, so container management features are negligible.

**Comment by CrunchylnMilk** [comment]
Short Answer: Not alone - try Podman.

Long Answer:
In the strictest sense yes; as the de facto implementation of the OCI spec, runc is the final software (other than linux primitives) invoked by many container software chains (including docker).

That said, though it can be, runc is not really meant to be invoked directly by the user - it's meant to be part of a containerization toolchain. An awful lot of setup, configuration, and preparation is required for Runc, and your security and absolutely depends on getting this configuration right. It is technically possible to do this security and network setup by hand, but discouraged in the strongest possible terms.

Personally, I would suggest you see if Podman is available on your platform. It is almost completely command compatible with docker (except for swarm and remote administration features), which means you can literally look at the docker documentation for how to do almost anything, change the word 'docker' to 'podman', and it will work fine. Like Docker, Podman uses runc under the hood, but uses the more traditional *nix fork/exec model. This means Podman has no daemon constantly running to consume resources, and does not have the glaring security hole of the docker socket. I have no commercial stake in Podman, but personally (and happily) use it instead of docker in production.

As a final warning, the usual caveats apply - containerization (with ANY container runtime) is not automatic security. Running a production application in a **properly configured** (strongest possible emphasis on properly configured) container can absolutely help harden against certain kinds of threat, but there's a LOT that goes into infrastructure security.

**Comment by cyphar** [comment]
Yeah, if you're familiar with how containers operate you can use runc directly as part of a larger custom container management system (and runc itself is production-ready -- it's used by effectively every deployment of Docker, Kubernetes, et al). But I wouldn't recommend using it directly unless you have very specific requirements that preclude the use of easier-to-use tools like podman/docker/lxd/etc.

**Comment by kolyshkin** [comment]
I guess this is now answered, so it can be closed.

I have added a note to README about using runc directly, based on the comments above (https://github.com/opencontainers/runc/pull/2714).

**Comment by Andreyooo** [comment]
I see, that helps a lot. Thank you for your clarification @CrunchylnMilk & @cyphar .
