### ISSUE TITLE
Support /proc/PID/attr/apparmor/exec in addition to /proc/PID/attr/exec

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2801]
Requested in https://github.com/docker/for-linux/issues/1199#issuecomment-774811300

> use /proc/self/attr/apparmor/exec instead of /proc/self/attr/exec.

**Comment by AkihiroSuda** [comment]
This is kinda enhancement, but probably we should have this in rc94 to rescue Arch Linux users.

**Comment by AkihiroSuda** [comment]
PR: https://github.com/opencontainers/runc/pull/2803

**Comment by cyphar** [comment]
Feels like this is a kernel regression (or rather, a regression by the Arch Linux maintainers). Why does `CONFIG_LSM=...,bpf` cause the AppArmor interface to disappear? We can support the new one but it feels like the upstream kernel devs (or Arch devs) should know this is breaking userspace.

**Comment by AkihiroSuda** [comment]
> Feels like this is a kernel regression (or rather, a regression by the Arch Linux maintainers).

Not a kernel regression, this is a configuration issue on Arch side: https://github.com/archlinux/svntogit-packages/commit/69cb8c2d2884181e799e67b09d67fcf7944d8408#diff-6503b30d816e211d1909eed3e1eff5f9105fdc48f5735921a59f4906f99415beR9406

> Why does CONFIG_LSM=...,bpf cause the AppArmor interface to disappear? 

Because it prioritize `bpf` over `apparmor`.
A workaround is to prepend `apparmor` before `bpf` in the kernel cmdline:  e.g., `apparmor=1 lsm=capability,lockdown,yama,apparmor,bpf`

**Comment by cyphar** [comment]
Sorry, that's what I meant by "regression by the Arch Linux maintainers". But yeah, I already LGTM'd the patch, just seems like the Arch folks should test config changes before releasing them. :shrug:

**Comment by anthraxx** [comment]
@cyphar It's not like we do not test config changes, our general purpose kernel always goes through the testing repository which requires approvals. Apparmor is not something we support out of the box and by default, hence it seems the testing audience overlooked implications causing by this.
However strictly speaking, this is still not a "configuration issue". It surely may create interference and uncovers a shortcoming here, but the issue is clearly a shortcoming of handling LSM specific expectations for the interface and not that we did an unreasonable and bad change.

**Comment by Foxboron** [comment]
@AkihiroSuda and fwiw, I do backport patches for runc/containerd/docker if I'm made aware of them :)

**Comment by Maryse47** [comment]
@anthraxx this issue is much beyond apparmor use with runc or docker. In fact Arch change of appending bpf to lsm list broke the legacy way of enabling major lsm with `security=<lsm_name>.` This affects apparmor, selinux and perhaps smack too. This breaks user configs that worked for years and tons of docs must be rewritten including Arch wiki. I have no idea why Arch needs to enable bpf lsm by default while it doesn't provide any bpf program that uses it but I don't think it was good idea and should be reconsidered.

**Comment by anthraxx** [comment]
@Maryse47 I understood that, but its the legacy interface after all. Arch Linux is a rolling release, at a certain point in time users are expected to adapt to more modern ways to declare this. As I've tried to point out, the implications of this didn't initially arise during the testing phase. Documentation and wiki pages are open to be contributed to and extend non legacy ways to configure such, but I believe discussing Arch Linux specifics at this level starts to really be off-topic for this thread.

**Comment by Maryse47** [comment]
> I understood that, but its the legacy interface after all. Arch Linux is a rolling release, at a certain point in time users are expected to adapt to more modern ways to declare this.

I would understand if this change brought any benefit for Arch users but you just trade legacy interface to enable some idle code that has zero support from distro side (even wiki has zero documentation about it), not sure if there is a single person who really uses bpf lsm on Arch but then they can enable it themselves just fine. AFAIK the logic behind enabling bpf was  - _it doesn't hurt_ - but now it was proved it did hurt some users so the assumptions were clearly wrong.

> As I've tried to point out, the implications of this didn't initially arise during the testing phase

I don't understand why this matters now while they arised after testing phase with real users. It only shows that testing phase was unfortunately insufficient but it isn't excuse for ignoring the problem.

> I believe discussing Arch Linux specifics at this level starts to really be off-topic for this thread.

The problem I see is Arch broke stuff without a reason and puts the burden of fixing it on someone else because _our testing didn't uncover the problem_. Such attitude doesn't build faith in Arch maintainership and is generally bad for relations with upstream projects.

**Comment by cyphar** [comment]
Okay, this thread isn't the best place for arguments about Arch maintainership.

@anthraxx The reason I said it was a configuration bug is that `/proc/self/attr/exec` is a very long-standing interface, and the reason why the kernel didn't remove it when they added the subdirectory version is precisely because removing it will break userspace programs. I just took a look, and this bug is not only present in runc -- [LXC has the exact same bug](https://github.com/lxc/lxc/blob/lxc-4.0.6/src/lxc/lsm/apparmor.c#L1138) and LXC is usually more up-to-date than us when it comes to kernel developments (in runc, I'm the only semi-regular kernel developer while LXC has several full-time kernel developers).

So while you may view this as a bug in userland, that's not historically how backwards-incompatible UAPI changes are treated in Linux. If a kernel change breaks userspace, it's never userspace's fault. Personally I still find it strange that LSMs now have this (new) behaviour where kernel configuration options change parts of the UAPI which are not expected to break. (My guess is that most LSM developers assume everyone uses libapparmor or libselinux -- which simply isn't the case. And AppArmor has caused backwards-incompatible changes in the past -- the most notable example being signal mediation, so it's hardly a new issue.)

**Comment by cyphar** [comment]
(Also it should be noted this interface was only added in Linux 5.8 -- I would argue that "was the only way of doing this operation two kernel releases ago" really doesn't count as a legacy interface!)
