### ISSUE TITLE
Support recursively-readonly mounts with mount_setattr (kernel 5.12)

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/runc#2823]
The current OCI mount with `options: ["rbind", "ro"]` is (surprisingly) not recursively read-only.

`mount_setattr(2)` introduced in [kernel 5.12](https://github.com/torvalds/linux/commit/2a1867219c7b27f928e2545782b86daaf9ad50bd) can be used for creating recursively-readonly bind mounts:

```c
struct mount_attr attr = {
  .attr_set   = MOUNT_ATTR_RDONLY,
};
rc = mount_setattr(-1, "/mnt/ro", AT_RECURSIVE, &attr, sizeof(attr));
```

runc implementation will need runtime spec PR to be approved: https://github.com/opencontainers/runtime-spec/pull/1090

**Comment by cyphar** [comment]
Yes please! Though it should be noted this is technically going to be a behavioural change in runc, because our current implementation (unless I'm mistaken) doesn't currently make mounts read-only recursively. (Funnily enough, `mount_settattr(2)` partially came out of discussions where I mentioned that `MS_REC|MS_RDONLY|MS_BIND|MS_REMOUNT` doesn't do what you'd expect -- because we were doing that in runc.)

**Comment by AkihiroSuda** [comment]
> Though it should be noted this is technically going to be a behavioural change in runc

I was thinking of keeping the current `["rbind","ro"]` behavior as-is (i.e., recursively writable), and adding new JSON fields for `MOUNT_ATTR_RDONLY`: https://github.com/opencontainers/runtime-spec/pull/1090

**Comment by cyphar** [comment]
Right, but I was thinking of `readonly: true` in particular -- currently that doesn't recursively mount the root as read-only, and it probably should (with the exception of `/proc`).

**Comment by AkihiroSuda** [comment]
Moving to v1.2 milestone, waiting for https://github.com/opencontainers/runtime-spec/pull/1090#issuecomment-902540248

**Comment by AkihiroSuda** [comment]
Opened PR https://github.com/opencontainers/runc/pull/3272
