### ISSUE TITLE
runc 1.0-rc93 doesn't exist in the repositories

### ISSUE THREAD

**Issue by lazystone** [opencontainers/runc#2853]
runc 1.0-rc93 doesn't exist in the repositories: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/

But latest cri-o 1.20.1 uses updated gocapability dependency, which causes cri-o/cri-o#4658

**Comment by thaJeztah** [comment]
You're missing a zero; it should be `v1.0.0-rc93`

**Comment by thaJeztah** [comment]
oh, nevermind, I read it wrong and thought you were looking for the tag in this repo

@cyphar ptal

**Comment by lazystone** [comment]
I'm not sure which team is responsible for packaging cri-o-runc though. Feel free to close if it's a wrong project for that issue.

**Comment by cyphar** [comment]
This is the upstream tracker for runc, which is really not the right place to be submitting bug reports for packaging issues on OBS. Please use https://bugzilla.opensuse.org/. (As an aside I was under the impression `devel:kubic` linked from `Virtualization:containers` but it looks like `devel:kubic:libcontainers:stable` has pinned versions of everything...).

**Comment by cyphar** [comment]
Actually `devel:kubic:libcontainers:stable` is actually maintained by Red Hat folks (the https://github.com/containers group). /cc @lsm5 -- where is the best place to direct bug reports?

**Comment by lsm5** [comment]
@haircommander ping, could you please bump `cri-o-runc` to v1.0.0-rc93 on kubic? https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/cri-o-runc ?

**Comment by lsm5** [comment]
my bad, seems like I had already done it for the kubic:libcontainers:testing project. Moved the files over to the stable project now. 

But, looks like the x86_64 package is failing to build because of some dependency issues, which I guess is a problem with OBS' setup itself. @haircommander could you look into that please? https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/cri-o-runc . May need to check with the OBS admins about it.
