### ISSUE TITLE
test Dockerfile failing because of criu

### ISSUE THREAD

**Issue by runcom** [opencontainers/runc#287]
`criu` has been removed from debian stable and testing due to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796536 (both 1.6.2 in stable and 1.7.2 in testing, it's only available in sid) and tests are failing both on host and CI
by any chance, can the dockerfile download and build the criu version runc is interested into to avoid this kind of issue?

ping @jfrazelle

**Comment by boucher** [comment]
It's certainly possible to built it ourselves. I did it this way because I was told people wanted to avoid dependency management. I'd be happy to make that change if needed. As an alternative (and this may be a bad suggestion), should we consider using the criu ppa on launchpad (https://launchpad.net/~criu/+archive/ubuntu/ppa)?
