### ISSUE TITLE
Seccomp Blocks 32bit syscalls

### ISSUE THREAD

**Issue by crosbymichael** [opencontainers/runc#290]
By default without adding any specific rules and having allow as the default action 32bit syscalls are blocked.  How do we unblock this without disabling all of seccomp?  

ping @mheon

**Comment by mheon** [comment]
This is easy enough to do with Libseccomp, just requires a call into the library to add a new architecture to the filter. I can see two potential ways of doing this for 32-bit:

First, just include the 32-bit version of an architecture by default - e.g. x86 if native architecture is AMD64, ARM if native arch is AARCH64. Simplest, but doesn't get the full security benefit we might get otherwise - increases the attack surface of a machine that doesn't actually use those syscalls.
Second, include a field in the config for additional architectures we wish to include in filters. This lets us keep the default very restrictive while allowing additional architectures if the situation calls for it.

My preference would be for the second approach.

**Comment by crosbymichael** [comment]
I think the second options sounds good but will have to look at the PR to see how I would use it as a user.  

Also just remember that it's a library and you cannot really make hard defaults for security because in the end it will break someone and if they don't have a way to configure it they will end up disabling the entire feature to get their stuff working again ( what I had to do ).

**Comment by mheon** [comment]
I created #295 to add support for this to the Libcontainer config. Going to need a PR to the spec to add the new Architectures field to the Seccomp configuration there, which would wire into this.

On defaults being too stringent: It would certainly be possible to add additional architectures to the config generated by `runc spec` based on what architecture you're presently running, allowing us to default to allowing x86 if you're on AMD64, though this does defeat the point of a platform-independent configuration file somewhat.

**Comment by crosbymichael** [comment]
it doesn't have to be the default, it just has to be configurable

**Comment by crosbymichael** [comment]
@mheon we merged the libcontainer update, can you open a PR on the specs repo?

**Comment by mheon** [comment]
@crosbymichael Can do.

**Comment by crosbymichael** [comment]
thanks!

**Comment by keloyang** [comment]
Is there  a plan that docker provide a user interface for seccomp ?
@mheon  @crosbymichael

**Comment by mheon** [comment]
@keloyang Yes, I'm working on a frontend to use Seccomp in Docker. I'm hoping to have a PR out for review sometime next week.

**Comment by mheon** [comment]
@crosbymichael Once #345 is merged, I think this can be closed

**Comment by crosbymichael** [comment]
This was merged and supported
