### ISSUE TITLE
starting container process caused: setup user: unable to find <user>: bufio.Scanner: token too long: unknown.

### ISSUE THREAD

**Issue by erict-square** [opencontainers/runc#3036]
### Problem

I'm running into the following problem when I run `docker run --network=host --hostname=<hostname> --user <user> -v /etc/group:/etc/group:ro <image>`.

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: setup user: unable to find groups for spec <user>: bufio.Scanner: token too long: unknown.
```

**My current finding shows me that this error is only thrown if a line in `/etc/group` exceeds 65536 characters.**

### Diagnosis 

I'm not familiar with runc code or golang, but i tried my best to find what's going on. I was able to find where this error message is thrown `unable to find groups for spec` in https://github.com/opencontainers/runc/blob/48d76adf7b8d074296edbc8c4475ebede1062116/libcontainer/user/user.go#L359

And from there, I find that the error likely came from running `ParseGroupFilter` function in https://github.com/opencontainers/runc/blob/48d76adf7b8d074296edbc8c4475ebede1062116/libcontainer/user/user.go#L339

Reading `ParseGroupFilter` function, https://github.com/opencontainers/runc/blob/48d76adf7b8d074296edbc8c4475ebede1062116/libcontainer/user/user.go#L178-L211, I suspect that we're hitting a token limit in `bufio.NewScanner` (which happens to be 65536 according to https://golang.org/pkg/bufio/#pkg-constants). This is likely given that another project https://github.com/sirupsen/logrus/issues/564  has hit a similar issue as well.

**Comment by kolyshkin** [comment]
There was a same bug in golang stdlib os/user (https://github.com/golang/go/issues/43636), which was fixed by https://github.com/golang/go/issues/43636.

I was looking at this bug and ended up implementing `GroupIds` for non-cgo/osusergo case in upstream (see https://go-review.googlesource.com/c/go/+/330753). Unfortunately it's a feature freeze for golang now, but once my changes will be merged, my plan is to
 - use stdlib as much as possible;
 - for GroupIds, copy the implementation, conditionally using it, depending on the go version, so that eventually we can get rid of the copy;
 - maybe eventually we can remove our user package entirely.

I will start working on it next week. It's a big job though.

Before that, though, let me try to cook a short fix that we can backport.

**Comment by erict-square** [comment]
@kolyshkin Thanks for the update and taking on this work! I'm really thrilled!

**Comment by kolyshkin** [comment]
Here's a quick and dirty fix: https://github.com/opencontainers/runc/pull/3062
