### ISSUE TITLE
runc version unknown 

### ISSUE THREAD

**Issue by ccnankai** [opencontainers/runc#3102]
After I executed the command, `apt-get install cri-o,cri-o-runc`  and `cri-o-runc --version` 
 the result I got is as follows. What went wrong.
![image](https://user-images.githubusercontent.com/33537489/126313117-7df2ad61-e756-4b50-b3d2-953d71b3a0a1.png)

**Comment by cyphar** [comment]
That's an issue with whoever is building the package you've installed -- the versions listed in `runc --version` are specified at build time, so the package builder is not filling in that information properly. Please report the issue with them. (The "unknown" string was added recently in order to allow less-than-ideally-built runc builds to work with Docker without any warnings. See #2956.)

**Comment by haircommander** [comment]
this is an issue with our OBS packaging. I'll take a look

**Comment by ccnankai** [comment]
When I use the `crictl runp pod.json` command to create a pod, it will report an error message:**Failed to create pod sandbox: rpc error: code = Unknown desc = failed to mount container....
error creating overlay mount to /var/lib/containers/storage/overlay merged invalid argument**
![image](https://user-images.githubusercontent.com/33537489/126337725-f46e37e3-894f-4b4b-9cc2-2f95cc9ae2d0.png)
as described in the question [https://github.com/cri-o/cri-o/issues/5104].
Does the creating overlay mount error have anything to do with this?

**Comment by haircommander** [comment]
nope @ccnankai that is a separate issue which we'll look into in https://github.com/cri-o/cri-o/issues/5104 :)

**Comment by AkihiroSuda** [comment]
Closing, as this seems an issue on the packager's side.

**Comment by haircommander** [comment]
fwiw I should have fixed the package!
