### ISSUE TITLE
remove Pausing state, update docs

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#3343]
This needs to be done after merging #3316.

The "Pausing" state of container is not used, and the Pause() docs incorrectly says that it works asynchronously.

Need to
 - remove Pausing state entirely;
 - update the docs (make them conform to golang style)

Ref: https://github.com/opencontainers/runc/pull/3316#discussion_r787643478

**Comment by danishprakash** [comment]
Hey @kolyshkin, is this something a new contributor to the project can pick up? Please correct me If I'm understanding it incorrectly, but is it as trivial as getting rid of the Pausing state(and all it's references) from within libcontainer and subsequently even runc?
https://github.com/opencontainers/runc/blob/5547b5774f71f75a088e7432fa961778750a0fbd/libcontainer/container.go#L23-L24

**Comment by kolyshkin** [comment]
@danishprakash yes, you can try removing `Pausing` state from this code entirely, feel free to open a PR.

In general, you can also contribute by reviewing existing PRs, suggesting improvements and asking questions in there.

**Comment by danishprakash** [comment]
Hey @kolyshkin I just noticed this is still open since we have one pending item on this issue. Just checking before I make changes, do we simply mean to update the docs to now reflect the removal of `Pausing` state? Also, when you say conforming to Golang style, do you mean docs in general or something else? Thanks

**Comment by kolyshkin** [comment]
This is now fully fixed, no pending tasks.
