### ISSUE TITLE
@test "runc run [seccomp] (empty listener path)" named badly

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#3415]
Here is the test:

https://github.com/opencontainers/runc/blob/51e607f2cdd8ccf7f39f29aab531d674e487b311/tests/integration/seccomp-notify.bats#L95-L105

Its name says "empty listener path" but it checks something different. I am not sure what, so summoning @mauriciovasquezbernal @rata to please take a look.

**Comment by rata** [comment]
@kolyshkin thanks for pulling us in.

There was a typo there, instead of "empty" that should be "non-empty". The idea is to test that we ignore the listenerPath if the profile doesn't use seccomp notify actions.

I will open a PR to fix that. Also, I re-read all the other tests in that file to make sure they are named correctly too. While doing so, I wrote a 1 line sentence for their intent, will include that in the PR too (as a different commit).

Thanks!
