### ISSUE TITLE
CI Flaky test: TestSkipDevicesTrue:  mkdir /sys/fs/cgroup/hugetlb/system.slice/system-runc_test_pods.slice: no such file or directory

### ISSUE THREAD

**Issue by rata** [opencontainers/runc#3743]
On centos-7, this failure occurs from time to time:
```
=== RUN   TestSkipDevicesTrue
    systemd_test.go:136: mkdir /sys/fs/cgroup/hugetlb/system.slice/system-runc_test_pods.slice: no such file or directory
--- FAIL: TestSkipDevicesTrue (0.07s)
```

**Comment by rata** [comment]
Here is another failure, probably related to the same underlying issue: https://cirrus-ci.com/task/6425762278932480?logs=unit_tests#L319

```
=== RUN   TestSkipDevicesTrue
    systemd_test.go:187: open /sys/fs/cgroup/cpuset/system.slice/system-runc_test_pods.slice/cpuset.mems: no such file or directory
--- FAIL: TestSkipDevicesTrue (0.25s)
```

**Comment by rata** [comment]
I'm not familiar with those parts of runc, so if anyone can help to debug this it would be great! :)

**Comment by rata** [comment]
There is no prow here :)

**Comment by rata** [comment]
So maybe it is related to some dirty state a test that runs before can leave? I mean, if running only that isolated test doesn't repro, that is the only idea that comes to mind now.

Other things might be the systemd version the CI vs you are using or some other system pkg/kernel.

**Comment by fahedouch** [comment]
hi @rata ,

thank for your insights. Indeed, re-running test in a non-isolated environnement produce some fails as shown above. 
After some debug, I feel the issue is coming from this [line](https://github.com/opencontainers/runc/blob/main/libcontainer/cgroups/fs/cpuset.go#L205), the program start [cpusetCopyIfNeeded](https://github.com/opencontainers/runc/blob/main/libcontainer/cgroups/fs/cpuset.go#L205) before ensuring that the content of cgoup current directory is totally  present. I cannot prove this for the moment.
