### ISSUE TITLE
Remove global option '--root'

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/runc#417]
The current specification requires/states that state.json files MUST be stored in '/run/opencontainer/containers'  The '--root' option makes runc non-compliant with the MUST requirement in the spec.

**Comment by tianon** [comment]
Why would the whole runtime be non-compliant because the user is given the
freedom to violate the spec by hand?

IMO this option would be useful for listing containers of a chroot without
having to chroot into it, for example, so I think it'd be better to
document that using the flag creates non-compliant containers, wouldn't it?

**Comment by mikebrow** [comment]
The way it was explained to me is MUST be type language is not optional language and does not allow for optionally not doing that which is in the MUST be type language... not when it comes to such types of compliance language. If the feature is a good needed feature the language in the spec should be changed to something like MUST at least include a default option where the files are stored in .... and MAY also include a published option to override said location.  Cheers :-)

I see Pros and Cons either way.  We were discussing some today in open containers chat.. perhaps we could discuss on the next Bluejean call.

**Comment by tianon** [comment]
Ah, I see; good point.  I'd personally be in favor of relaxing the spec
there to allow runtime configuration but ensure all runtimes must have the
same default configuration or something like that.  Dunno if I'm a minority
but I'd be happy to help bikeshed language to that effect!

At the very least I think we need to adjust to account for variations of
the FHS in active use (which means /var/run should likely be permissible
too IIRC, been too long since I read the FHS).

**Comment by mikebrow** [comment]
To your point about '--root' and chroot... hmm.   After typing up the PR for the ps command we were talking about the problem of storing what --root 's are being used. While you might want to use --root to see into a child's container list... what if the child's container list isn't in the default location...  Just thinking outloud.

**Comment by mikebrow** [comment]
If you like I could take a swing at adding a -recurse option to the runc ps command to cover grabbing lists of containers running in chroot jails.

**Comment by mikebrow** [comment]
Great point, it would not be good for the spec to preclude perfectly valid and widely used linux configurations... :-)

**Comment by mikebrow** [comment]
From: https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard
Run-time variable data. This directory contains system information data describing the system since it was booted.[8]

In FHS 3.0, /var/run is replaced by /run; a system should either continue to provide a /var/run directory, or provide a symbolic link from /var/run to /run, for backwards compatibility.[9]

**Comment by tianon** [comment]
Right, I remember that part, but I think there are still distros using FHS
2. :(

**Comment by mikebrow** [comment]
I'll bet they support symlinks :-)

**Comment by tianon** [comment]
Debian is still rocking 2.3, but I think they do include a symlink in this
case.

**Comment by duglin** [comment]
We should probably move this to the 'spec' repo since we're really talking about a spec change, but... I thought this was mandated so that 3rd party tooling knew where to look for the state info on the containers. If each running instance of 'runc' specified a different root location, I'm not sure how a 3rd party tool would know where to look, at least not w/o some kind of synchronization between it and each runc instance.

Just tossing out ideas, but one option is to punt.  Allow --root on each runc instance and assume that there's something above runc managing all of this. Which means the 3rd partying tooling would need to interact with that higher-level exe (to find out where/how to get the state info) and not runc directly.  Of course, the downside to this is that runc becomes less stand-alone (in a sense) and in order for us to have some kind of interoperable solution we may need to define that higher level exe. Guess it depends on how usable runc is supposed to be on its own w.r.t. integration with other tools.

We should probably discuss the interaction pattern/design of runc with its users and other tooling. We've briefly discussed standardizing the runc cmd line syntax, and we may need to add introspection and discovery (of runc instances and state data) to that discussion.

**Comment by crosbymichael** [comment]
We removed this requirement from the spec so this option is safe to keep.
