### ISSUE TITLE
docker exec is not limit when run with --pid-limit

### ISSUE THREAD

**Issue by kamizjw** [opencontainers/runc#4413]
### Description

start a container with pid-limit，like ```docker run -d --pids-limit 5 57c4aa05e472 bash -c "sleep 1000"```.Then many exec processes were started, exceeding the pid-limit limit，exec process is not limit.

### Steps to reproduce the issue

1. docker run -d --pids-limit 5 57c4aa05e472 bash -c "sleep 1000
2. docker exec $container_id bash -c "sleep 1000"

### Describe the results you received and expected

NA

### What version of runc are you using?

runc version 1.1.8

### Host OS information

Linux 6.6.aarch64

**Comment by kamizjw** [comment]
I have tried the latest version of runc and it behaves the same as version 1.1.8. I checked the code. Runc init is created first and then added to the cgroup.This method is indeed technically unrestricted in cgroup.But judging from the phenomenon, runc can always create exec processes without being restricted by pid-limit. Is this reasonable?

**Comment by cyphar** [comment]
Are you saying that you ran many `docker exec`s and that exceeded the limit?

That is intentional. The kernel does not restrict migrating processes to cgroups (because it's an administrative operation) and so the pids cgroup could have more processes than the limit. The only thing restricted by the pids cgroup is *forks*. If you try to run some subprocesses in one of your `docker exec`s you should get an error.

**Comment by kamizjw** [comment]
OK，i get it, thanks

**Comment by cyphar** [comment]
Cool, closing then. Thanks for reaching out to ask!
