### ISSUE TITLE
exec

### ISSUE THREAD

**Issue by jfrazelle** [opencontainers/runc#477]
I'm going to "fix" exec, what would you like: `runc exec [command]`?

**Comment by marcosnils** [comment]
@jfrazelle seems that's what I'd expect. When you do it remind me to buy you some beers :beers:

**Comment by duglin** [comment]
@mikebrow might be looking at this too.
Supporting `[command]` on the cmd line for `start` would be nice as well  :+1:

**Comment by jfrazelle** [comment]
ya i want that too next :) hehehe

**Comment by jfrazelle** [comment]
should `-t` be a flag or no?

**Comment by mikebrow** [comment]
What I was thinking was instead of exec using a path to a process config I was proposing we change it to be a command / executable that uses the defaults for process config information from the already started process. This would allow runc exec bash/ls etc. without having to create a process.config for each command. Then add some kind of --config option to the exec to explicitly point to a process config for the command to override the process config used for start is not acceptable for the command being executed...; or we could just have a few --conf_* param options; or we could have a list of "foo"="this" options for the config for specifically overriding stuff.

**Comment by duglin** [comment]
we need to be a little careful here since `runc` isn't just a piece of code, its meant to be a reference implementation of a spec.  Right now the spec says that the config.json MUST be in the same dir as the rootfs. Which means `runc start cmd` should update the config file and that specifying `cmd` on the cmd line instead of having to edit `config.json` by hand is just a runc extension/convenience.
