### ISSUE TITLE
Failed to found existing config.json withing runc exec command

### ISSUE THREAD

**Issue by dobegor** [opencontainers/runc#530]
I have a container running an alpine image, with a basic shell started.
In another tab of the terminal (in the same directory) I executed 
```sudo runc exec -t /bin/sh```, (trying to launch another shell inside and attach to it)
but I was given the error: 
```FATA[0000] exec failed: JSON specification file config.json not found```
Obviously, the config.json is there, because it's the file I used to start a container.
What's wrong?

**Comment by jfrazelle** [comment]
and you are in the same directory?

**Comment by jfrazelle** [comment]
whats the git sha of the binary you are running

**Comment by dobegor** [comment]
sure thing.
```
alpine ⟩ pwd
/home/dobegor/tmp/alpine
alpine ⟩ ls
bin/  config.json  dev/  etc/  home/  lib/  linuxrc@  media/  mnt/  proc/  root/  run/  runtime.json  sbin/  sys/  tmp/  usr/  var/
```
latest pull, 86454a0

**Comment by jfrazelle** [comment]
why is your rootfs in that dir too? and not a subdir? i've never done that i guess it's possible

**Comment by dobegor** [comment]
@jfrazelle I just went by a tutorial on runc.io main page.
I ran a docker image, exported it, unarchived, generated specs, set rootfs to "." and it runs ok with that config.json, but exec doesn't work.

**Comment by dobegor** [comment]
@jfrazelle moving to a separate rootfs folder fixed that
it's ok, but I think it should be mentioned in runc.io main page mini-guide.
thanks

**Comment by rajasec** [comment]
@jfrazelle 
Earlier runc exec use to run with config.json exists in same directory, but now it is saying config.json not found
Infact it exists in the same directory which used for start

Steps followed
./runc start
I modified config.json to start the process
./runc exec config.json  
Above fails, "no such file or directory"

**Comment by mikebrow** [comment]
We are not currently storing the bundle directory in the container or the original rootfs path from the config.  We only store absolute rootfs path when the container was started.  When exec is run it makes the assumption that the bundle is in the directory above the roofts path.  This code logic won't work when the rootfs is not a subdirectory.  We have another issue being tracked for version 0.9 to store the bundle directory so that the runc list command can show said directory.  See issue #548 When that is fixed we can also fix this issue.  Cheers.

**Comment by crosbymichael** [comment]
Thanks @mikebrow, closing
