### ISSUE TITLE
Sharing /dev/ with the container breaks /dev/ptmx on the host

### ISSUE THREAD

**Issue by willmtemple** [opencontainers/runc#80]
When a container is launched with a bind mount between /dev (on the host) and /dev (in the container), all subsequent attempts to open /dev/ptmx fail.

`setupPtmx()` in `libcontainer/rootfs_linux.go` will unconditionally remove `/dev/ptmx` and then symlink it to `/dev/pts/ptmx` , which is a character file that is untouchable by unprivileged users. This prevents unprivileged programs which rely on `getpt` from running on the host (such as X terminals, screen, and tmux).

I discovered this via docker, but it happens in any libcontainer app if /dev/ is shared with the container before `setupPtmx`. Is there a reason for libcontainer to touch /dev (at all) if it's mounted directly from the host? I have tested this on Fedora 22 and 21, SELinux is set to permissive, as well as Arch Linux without SELinux.

I can reproduce this consistently.

`uname -a`: `Linux wtemple.localdomain 4.0.6-300.fc22.x86_64 #1 SMP Tue Jun 23 13:58:53 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

`config.json`:
```
{
    "version": "0.1.1",
    "platform": {
        "os": "linux",
        "arch": "amd64"
    },
    "process": {
        "terminal": true,
        "user": "root",
        "args": [
            "/bin/sh"
        ],
        "env": [
            "PATH=/bin,/sbin"
        ],
        "cwd": ""
    },
    "root": {
        "path": "rootfs",
        "readonly": true
    },
    "hostname": "shell",
    "mounts": [
        {
            "type": "proc",
            "source": "proc",
            "destination": "/proc",
            "options": ""
        },
        {
            "type": "sysfs",
            "source": "sysfs",
            "destination": "/sys",
            "options": "nosuid,noexec,nodev"
        },
        {
            "type": "bind",
            "source": "/dev",
            "destination": "/dev",
            "options": "bind"
        }
    ],
    "linux": {
        "namespaces": [
            {
                "type": "process"
            },
            {
                "type": "network"
            },
            {
                "type": "mount"
            },
            {
                "type": "ipc"
            },
            {
                "type": "uts"
            }
        ],
        "capabilities": [
            "AUDIT_WRITE",
            "KILL",
            "NET_BIND_SERVICE"
        ],
        "devices": [
            "null"
        ]
    }
}
```

**Comment by disneyworldguy** [comment]
This seems to be due to the default SELinux policy for a Fedora system which includes:

> $ sudo semanage fcontext -l | grep ptmx
> /dev/ptmx                                          character device   system_u:object_r:ptmx_t:s0 

This omits the Symlink that replaces the character device. The following resolves the condition in my testing:

> $ sudo semanage fcontext -a -f l -t ptmx_t /dev/ptmx

I would recommend:

> $ diff -up docker.fc.bak docker.fc 
> --- docker.fc.bak       2016-03-08 11:33:38.894580384 -0500
> +++ docker.fc   2016-03-08 11:33:52.348740405 -0500
> @@ -1,5 +1,7 @@
>  /root/\.docker gen_context(system_u:object_r:docker_home_t,s0)
>  
> +/dev/ptmx                       -l      gen_context(system_u:object_r:devpts_t:s0)
> +
>  /usr/bin/docker                        --      gen_context(system_u:object_r:docker_exec_t,s0)
>  
>  /usr/lib/systemd/system/docker.service         --      gen_context(system_u:object_r:docker_unit_file_t,s0)

- Kyle

**Comment by AkihiroSuda** [comment]
docker/docker#21808 is hitting this issue again.

https://github.com/opencontainers/runc/pull/96#issuecomment-127741261 introduced `setupDev := len(config.Devices) != 0` for this issue.
https://github.com/opencontainers/runc/blob/55aabc142c005cd732614e1af985902814a1f704/libcontainer/rootfs_linux.go#L56

But I'm not sure there is any path that sets `setupDev` to `false`, because `config.Devices` seems to be  always set to non-empty in `spec_linux.go: createDevices()`.
* `createDevices`: https://github.com/opencontainers/runc/blob/6c88a526cdd74aab90cc88018368c452c7294a06/libcontainer/specconv/spec_linux.go#L456
* `CreateLibcontainerConfig`: https://github.com/opencontainers/runc/blob/6c88a526cdd74aab90cc88018368c452c7294a06/libcontainer/specconv/spec_linux.go#L200
* `createContainer`: https://github.com/opencontainers/runc/blob/6c88a526cdd74aab90cc88018368c452c7294a06/utils.go#L178
* `startContainer`: https://github.com/opencontainers/runc/blob/6c88a526cdd74aab90cc88018368c452c7294a06/start.go#L118
