### ISSUE TITLE
Support updates to parent devices cgroup hierarchies

### ISSUE THREAD

**Issue by dubstack** [opencontainers/runc#932]
#### Issue
Allowing or denying all devices by writing 'a' to devices.allow or devices.deny is
not possible once the device cgroups has children. The devices set() should skip writing 'a' to files when the device cgroup has children. 

#### Why this is needed:
I am currently working on introducing a cgroup hierarchy in the node in Kubernetes. See (https://github.com/kubernetes/kubernetes/issues/27204)

For the work I need to create a multi level cgroup hierarchy and support dynamic updates to a cgroup's resource parameters having children cgroups. 
This is currently not possible with libcontainer fs.Set() method. 

@cyphar What is your opinion on this? 

Even though I can have this logic in Kubernetes but I believe this should ideally be in libcontainer. If we agree on this I can send in a patch for the same.

cc @vishh @derekwaynecarr

**Comment by vishh** [comment]
@dubstack another way to summarize the issue is to say that the current cgroups API doesn't support updating parent cgroups hierarchies. I can't think of a reason why libcontainer cannot support it, except for the fact that it was not implemented with such an use case in mind. 

IIUC, the fix should be straight forward. I'd recommend posting a PR to fix it.

**Comment by dubstack** [comment]
Okay I will send out a patch.

**Comment by cyphar** [comment]
I'm confused what your proposed solution is? From what I can see, you're just saying that we should ignore changes to the devices cgroup if the cgroup has children? Why is the caller trying to change the devices cgroup in that case, if it knows that it has subcgroups? I don't really like ignoring errors (**especially** since the devices cgroups is a security feature).

**Comment by vishh** [comment]
The current issue is that we update `device` cgroups all the time. There is
no "ignore device cgroups" option.

**Comment by dubstack** [comment]
>  I'm confused what your proposed solution is? 
Make the Resources.AllowAllDevices a pointer. A user can skip specifying the value if he doesn't wants to update the cgroups devices. In the devices cgroup logic we would not write 'a' in devices.deny/ allow when the AllowAllDevices is nil.
> From what I can see, you're just saying that we should ignore changes to the devices cgroup if the cgroup has children? 
Ideally we would want libcontainer to determine if a cgroup has children and ignore updates to devices cgroup on such parent cgroups.
> Why is the caller trying to change the devices cgroup in that case, if it knows that it has subcgroups? 
I would like to use the fs.Manager.Set() method for updating all subsystem cgroups. 
> I don't really like ignoring errors (especially since the devices cgroups is a security feature).
We still error out if a user tries to set AllowAllDevices on a parent cgroup. So we can have that logic as it is.

**Comment by dubstack** [comment]
Closing this issue as #958 provides a temporary fix for this.
